# Generated by Django 6.1 on 2026-08-25 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mudanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_origen', models.CharField(max_length=255)),
                ('direccion_destino', models.CharField(max_length=255)),
                ('tamano', models.CharField(choices=[('CHICA', 'Chica (pocas cajas)'), ('MEDIANA', 'Mediana (muebles básicos)'), ('GRANDE', 'Grande (casa completa)')], default='CHICA', max_length=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Buscando transporte'), ('ASIGNADA', 'Transporte asignado'), ('FINALIZADA', 'Completada')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudanzas_pedidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudanzas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
