# Generated by Django 6.1 on 2026-08-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mudanza'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reputacion',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
    ]
