# Generated by Django 6.1 on 2026-08-26 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_reputacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ofrece_embalaje_seguro',
            field=models.BooleanField(default=False, help_text='Incluye operarios con bodycam y registro de cajas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='zona_cobertura',
            field=models.CharField(choices=[('SOLO_CABA', 'Solo Capital Federal'), ('SOLO_PBA', 'Solo Provincia de Buenos Aires'), ('CABA_A_PBA', 'Capital Federal a Provincia'), ('PBA_A_CABA', 'Provincia a Capital Federal'), ('TODAS', 'CABA y Provincia (Ambos sentidos)')], default='TODAS', max_length=20),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_escritas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
