# Generated by Django 6.1 on 2026-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_ofrece_embalaje_seguro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cuit',
            field=models.CharField(blank=True, help_text='Solo números, sin guiones', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiene_seguro',
            field=models.BooleanField(default=False, help_text='¿Cuenta con seguro de carga?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vehiculo_principal',
            field=models.CharField(blank=True, choices=[('FURGON', 'Furgón (Ej: Kangoo, Partner)'), ('CAMIONETA', 'Camioneta (Ej: F-100, Hilux)'), ('CAMION_CHICO', 'Camión Liviano (Ej: 350)'), ('CAMION_MUDANZA', 'Camión de Mudanza Grande')], max_length=20, null=True),
        ),
    ]
