# Generated by Django 6.1 on 2026-08-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_cuit_usuario_direccion_base_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descripcion_servicio_premium',
            field=models.TextField(blank=True, help_text='Describe qué incluye tu servicio extra', null=True),
        ),
    ]
