# Generated by Django 6.1 on 2026-08-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_descripcion_servicio_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudanza',
            name='fecha_mudanza',
            field=models.DateField(null=True),
        ),
    ]
