# Generated by Django 6.1 on 2026-09-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mudanza_fecha_mudanza'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudanza',
            name='codigo_postal_destino',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='codigo_postal_origen',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
