# Generated by Django 6.1 on 2026-09-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mudanza_codigo_postal_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudanza',
            name='solicita_servicio_premium',
            field=models.BooleanField(default=False),
        ),
    ]
