# Generated by Django 6.1 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mudanza_solicita_servicio_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudanza',
            name='fecha_propuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='mudanza',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Buscando transporte'), ('ASIGNADA', 'Transporte asignado'), ('COTIZADA', 'Cotizada'), ('FINALIZADA', 'Completada')], default='PENDIENTE', max_length=15),
        ),
    ]
