# Generated by Django 6.1 on 2026-09-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mudanza_fecha_propuesta_mudanza_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudanza',
            name='costo_distancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='costo_operarios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='costo_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='tipo_viaje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
