# Generated by Django 6.1 on 2026-09-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mudanza_costo_distancia_mudanza_costo_operarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudanza',
            name='cargos_extra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mudanza',
            name='detalle_cargos_extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
