# Generated by Django 6.1 on 2026-09-07 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mudanza_cargos_extra_mudanza_detalle_cargos_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resena',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='mudanza',
            name='tiene_resena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ - Excelente'), (4, '⭐⭐⭐⭐ - Muy Bueno'), (3, '⭐⭐⭐ - Bueno'), (2, '⭐⭐ - Regular'), (1, '⭐ - Malo')], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resena',
            name='mudanza',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='resena', to='core.mudanza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resena',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_dadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resena',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
