# Generated by Django 6.1 on 2026-09-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_fecha_resena_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cubre_caba_caba',
            field=models.BooleanField(default=True, verbose_name='CABA a CABA'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cubre_caba_provincia',
            field=models.BooleanField(default=True, verbose_name='CABA a Provincia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cubre_interior',
            field=models.BooleanField(default=False, verbose_name='Viajes al Interior'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cubre_provincia_caba',
            field=models.BooleanField(default=True, verbose_name='Provincia a CABA'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cubre_provincia_provincia',
            field=models.BooleanField(default=True, verbose_name='Provincia a Provincia'),
        ),
    ]
