# Generated by Django 6.1 on 2026-09-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usuario_cubre_caba_caba_usuario_cubre_caba_provincia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cubre_caba_caba',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cubre_caba_provincia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cubre_provincia_caba',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cubre_provincia_provincia',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cubre_amba',
            field=models.BooleanField(default=True, verbose_name='AMBA (Conurbano)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cubre_caba',
            field=models.BooleanField(default=True, verbose_name='Solo CABA'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cubre_resto_pba',
            field=models.BooleanField(default=False, verbose_name='Resto de PBA (Ej: La Plata, Costa)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cubre_interior',
            field=models.BooleanField(default=False, verbose_name='Interior del País'),
        ),
    ]
